import Head from "next/head";

export const PageHead = () => (
  <Head>
    <title>Sign in to our app!</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);
