name: Code Quality

on:
  push:
    branches:
      - "*"

jobs:
  code-quality:
    name: Lint & test source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "^14.17.0"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-dbm-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-dbn-${{ env.cache-name }}-
            ${{ runner.OS }}-dbm-
      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test
